import Head from "next/head";
import Image from "next/image";
import Adnav from "../components/navigation/Adnav";
import { useMediaQuery, Hidden } from "@mui/material";
import MobileNav from "../components/navigation/mobile/MobileNavigation";
import DesktopNav from "../components/navigation/desktop/DesktopNavigation.tsx";
import Banner from "../components/main/Banner.tsx";
import ProductList from "../components/products/ProductList";
import ServiceCards from "../components/ServiceCards";
import PostSection from "../components/PostSection";

export default function Home() {
  const isMobile = useMediaQuery((theme) => theme.breakpoints.down("lg"));

  return (
    <div>
      <Head>
        <title>frontend-task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Adnav />
      {isMobile ? (
        <Hidden lgUp implementation="css">
          <MobileNav />
        </Hidden>
      ) : (
        <Hidden mdDown implementation="css">
          <DesktopNav style={isMobile ? {} : { marginTop: "4rem" }} />
        </Hidden>
      )}
      <Banner />
      <ProductList />
      <ServiceCards />
      <PostSection />
    </div>
  );
}
